# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
    - echo Installing source NPM dependencies...
    - npm install
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
  - server/**/*
  - package.json
  - node_modules/**/*
  - README.md